version: '3.7'

services:
  komodod:
    build:
      dockerfile: Dockerfile
    image: greerso/komodo-docker:latest
    networks:
        - komodo-net
    ports:
        - '${P2P_PORT}:${P2P_PORT}'
    volumes:
        - ~/.komodo:${HOME}/.komodo
        - ~/.zcash-params:${HOME}/.zcash-params
    command: ["bin/komodod","-printtoconsole","-pubkey=${PUBKEY}"]
    restart: always

networks:
  docker-net:
    driver: bridge